version: '3'
services:
  postgresjm:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=adam
      - POSTGRES_DB=lab_bd
    ports:
      - "5400:5432"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql

  pgadmin-composejm:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5444:80"
    depends_on:
      - postgresjm
