version: '3'
services:
  postgresjm:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab_bd
    ports:
      - "5400:5432"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
