version: '3'
services:
  postgresjm:
    image: "postgres:15.2-alpine"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=IAMTHEONE@123
      - POSTGRES_DB=lab_bd
    ports:
      - "5400:5432"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
