version: '3'
services:
  postgresjm:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=IAMTHEONE@!
      - POSTGRES_DB=lab_bd
    ports:
      - "64901:7892"
    expose:
      - "7892"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
